name: credit_bank_project

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-bank
    environment:
      POSTGRES_DB: deal_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./DealMS/src/main/java/app/gozenko/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d deal_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper-bank
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "2182:2181"
    networks:
      - bank-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-bank
    depends_on:
      zookeeper:
        condition: service_started
        required: true
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "18000"
    networks:
      - bank-network
    restart: unless-stopped

  deal-ms:
    build:
      context: .
      dockerfile: DealMS/Dockerfile
    container_name: deal-ms
    depends_on:
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8086:8084"
    networks:
      - bank-network
    restart: unless-stopped

  calculator-ms:
    build:
      context: .
      dockerfile: CalculatorMS/Dockerfile
    container_name: calculator-ms
    depends_on:
      - deal-ms
    ports:
      - "8085:8084"
    networks:
      - bank-network
    restart: unless-stopped

  statement-ms:
    build:
      context: .
      dockerfile: StatementMS/Dockerfile
    container_name: statement-ms
    depends_on:
      - deal-ms
    ports:
      - "8087:8084"
    networks:
      - bank-network
    restart: unless-stopped

  dossier-ms:
    build:
      context: .
      dockerfile: DossierMS/Dockerfile
    container_name: dossier-ms
    depends_on:
      kafka:
        condition: service_started
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8088:8084"
    networks:
      - bank-network
    restart: unless-stopped

  gateway-ms:
    build:
      context: .
      dockerfile: GatewayMS/Dockerfile
    container_name: gateway-ms
    depends_on:
      - deal-ms
      - calculator-ms
      - statement-ms
    ports:
      - "8089:8084"
    networks:
      - bank-network
    restart: unless-stopped

networks:
  bank-network:
    driver: bridge
    name: bank-network

volumes:
  postgres-data:
    name: postgres-bank-data