spring.application.name=StatementMS
server.port=8087

app.gozenko.legal-age=18

app.gozenko.deal-url=http://localhost:8086
app.gozenko.path-offer=/api/v1/deal/offer/select
app.gozenko.path-statement=/api/v1/deal/statement
