spring.application.name=StatementMS
server.port=8087

app.gozenko.legal-age=18

app.gozenko.deal-url=http://localhost:8086/api/v1/deal
app.gozenko.uri-offer=/offer/select
app.gozenko.uri-statement=/statement
