spring.application.name=gateway
server.port=8089

app.gozenko.statement-url=http://localhost:8087/api/v1/statement
app.gozenko.deal-url=http://localhost:8086/api/v1/deal

app.gozenko.uri-statement=/
app.gozenko.uri-offer=/offer
app.gozenko.uri-credit=/calculate/{statementId}
app.gozenko.uri-send-documents=/document/{statementId}/send
app.gozenko.uri-sign-documents=/document/{statementId}/sign
app.gozenko.uri-verify=/document/{statementId}/code/{code}