spring.application.name=gateway
server.port=8089

app.gozenko.statement-url=http://localhost:8087
app.gozenko.deal-url=http://localhost:8086

app.gozenko.path-statement=/api/v1/statement
app.gozenko.path-offer=/api/v1/statement/offer
app.gozenko.path-credit=/api/v1/deal/calculate/{statementId}
app.gozenko.path-send-documents=/api/v1/deal/document/{statementId}/send
app.gozenko.path-sign-documents=/api/v1/deal/document/{statementId}/sign
app.gozenko.path-verify=/api/v1/deal/document/{statementId}/code/{code}