server.port=8084

spring.datasource.url=jdbc:postgresql://postgres-db:5432/deal_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changeLog/db.changelog-master.xml

spring.kafka.bootstrap-servers=kafka:9092

app.gozenko.calculator-url=http://calculator-ms:8084