spring.application.name=calculator
server.port=8085

app.gozenko.base-percent=100
app.gozenko.base-rate=20
app.gozenko.legal-age=18
app.gozenko.insurance=3
app.gozenko.rate-salary-client=2
app.gozenko.rate-manager=2
app.gozenko.rate-topmanager=3
app.gozenko.rate-married=2
app.gozenko.rate-divorced=1
app.gozenko.rate-with-age=3
app.gozenko.rate-with-dependent=1